#!/usr/bin/env python3
"""Build the stylized 9-bus Oʻahu transmission network used by the DC-OPF study.

Load zones are the seven Oʻahu judicial districts, which the Census publishes as county
subdivisions (CCDs). Populations and tract geometry come from TIGERweb, which serves the
2020 P.L. 94-171 counts without an API key.

Two adjustments turn those seven districts into nine model buses:

1. Bus coordinates are population-weighted 2020 census-tract centroids rather than CCD
   internal points. The Honolulu CCD legally extends across the Northwestern Hawaiian
   Islands, so its geometric internal point falls roughly 500 miles from Oʻahu.

2. The Ewa CCD is split into three buses. Point-in-polygon on EIA-860 coordinates puts
   every one of the six modeled Oʻahu plants inside Ewa - the district runs from Kapolei to
   Mililani, about twenty miles. Left whole it would place 100% of island generation at a
   single node and erase exactly the injection geography this dataset exists to represent.

Branch topology follows Hawaiian Electric's published description of two transmission
corridors, one north and one south. Every electrical parameter on those branches is an
explicit assumption and is labeled as one in the output.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import pandas as pd
import requests


ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data" / "raw"
PROCESSED = ROOT / "data" / "processed"
EIA860_PLANT = RAW / "eia8602024" / "2___Plant_Y2024.xlsx"
FLEET = PROCESSED / "oahu_generators.csv"

CCD_GEOJSON = RAW / "tigerweb_census2020_honolulu_county_subdivisions.geojson"
TRACT_JSON = RAW / "tigerweb_census2020_honolulu_tracts.json"

TIGERWEB = (
    "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/"
    "tigerWMS_Census2020/MapServer"
)
COUNTY_SUBDIVISION_LAYER = 20
TRACT_LAYER = 6
HONOLULU_COUNTY = {"state": "15", "county": "003"}

PLANT_CODES = {765, 766, 10334, 54646, 56329, 60328}
KAHE_PLANT_CODE = 765

# Modeling decision, not Census geography. -158.075 W falls in the undeveloped gap between
# the Kapolei industrial area and West Loch, separating the Campbell Industrial Park
# complex from the Pearl Harbor corridor. Kahe is pulled out separately: at 582 MW it is
# the largest single injection on the island and sits on the leeward coast, physically
# apart from Campbell Industrial Park.
EWA_SPLIT_LONGITUDE = -158.075
EWA_WEST = "Ewa-West"
EWA_CENTRAL = "Ewa-Central"
KAHE = "Kahe"

# Electrical base. Oʻahu's bulk transmission is 138 kV (Hawaiian Electric, Power Delivery).
BASE_KV = 138.0
BASE_MVA = 100.0
Z_BASE_OHM = BASE_KV**2 / BASE_MVA  # 190.44 ohm

# Typical 138 kV overhead line constants. These are technology defaults, not HECO data.
X_OHM_PER_MILE = 0.80
R_OHM_PER_MILE = 0.12
# Straight-line bus separation understates conductor length; Oʻahu's terrain forces routing
# around the Waiʻanae and Koʻolau ranges.
ROUTING_FACTOR = 1.25
# Thermal rating of one 138 kV circuit on typical conductor.
MW_PER_CIRCUIT = 200.0
# Copper-plate peak-hour marginal cost from the baseline model (analysis_summary.csv). Used
# only to price the transport term; it is not itself a network parameter.
REFERENCE_LMP_USD_PER_MWH = 134.48

# Hawaiian Electric: "most of the power is generated by plants located on the west side of
# the island. Electricity is delivered throughout the island through two primary
# transmission corridors - one in the north and the other in the south."
# https://www.hawaiianelectric.com/about-us/power-facts/power-delivery
#
# Nine buses and ten branches leave two independent loops. That matters: on a radial
# network the DC-OPF and transportation formulations have identical feasible sets and the
# whole comparison this dataset exists to support would collapse.
BRANCHES = [
    (KAHE, EWA_WEST, "leeward generation tie", 2),
    (KAHE, "Waianae", "north corridor, leeward coast", 1),
    (EWA_WEST, EWA_CENTRAL, "south corridor, industrial to Pearl Harbor", 2),
    (EWA_CENTRAL, "Honolulu", "south corridor, urban import path", 3),
    ("Honolulu", "Koolaupoko", "Koʻolau crossing to the windward side", 1),
    ("Waianae", "Waialua", "north corridor, leeward coast", 1),
    ("Waialua", "Wahiawa", "north corridor, central", 1),
    ("Wahiawa", EWA_CENTRAL, "central tie to the Pearl Harbor corridor", 2),
    ("Waialua", "Koolauloa", "north shore", 1),
    ("Koolauloa", "Koolaupoko", "windward coast", 1),
]

EARTH_RADIUS_MILES = 3958.7613


def fetch_json(path: Path, layer: int, out_fields: str, geometry: bool) -> dict:
    """Query a TIGERweb layer for Honolulu County, caching the raw response in data/raw."""
    if path.exists() and path.stat().st_size:
        print(f"Using existing {path.relative_to(ROOT)}")
        return json.loads(path.read_text())

    params = {
        "where": f"STATE='{HONOLULU_COUNTY['state']}' AND COUNTY='{HONOLULU_COUNTY['county']}'",
        "outFields": out_fields,
        "returnGeometry": "true" if geometry else "false",
        "f": "geojson" if geometry else "json",
        "resultRecordCount": 2000,
    }
    if geometry:
        params["outSR"] = "4326"

    response = requests.get(f"{TIGERWEB}/{layer}/query", params=params, timeout=180)
    response.raise_for_status()
    payload = response.json()
    if "error" in payload:
        raise RuntimeError(f"TIGERweb error for layer {layer}: {payload['error']}")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=1, sort_keys=True))
    print(f"Downloaded {path.relative_to(ROOT)}")
    return payload


def rings(geometry: dict) -> list[list[list[float]]]:
    """Flatten a GeoJSON Polygon or MultiPolygon into a list of exterior/interior rings."""
    if geometry["type"] == "Polygon":
        return geometry["coordinates"]
    return [ring for polygon in geometry["coordinates"] for ring in polygon]


def in_ring(lon: float, lat: float, ring: list[list[float]]) -> bool:
    """Even-odd ray casting. Avoids a geometry dependency for nine small polygons."""
    inside = False
    count = len(ring)
    for index in range(count):
        x1, y1 = ring[index][0], ring[index][1]
        x2, y2 = ring[(index + 1) % count][0], ring[(index + 1) % count][1]
        if (y1 > lat) != (y2 > lat):
            crossing = x1 + (lat - y1) * (x2 - x1) / (y2 - y1)
            if lon < crossing:
                inside = not inside
    return inside


def locate(lon: float, lat: float, districts: dict[str, list]) -> str | None:
    """Return the district whose boundary contains the point, if any.

    Verified against the Census geocoder's own point-in-polygon for all six plant
    coordinates; the two boundary cases, Kahe and Schofield, agree.
    """
    for name, boundary in districts.items():
        # Ring order in these MultiPolygons is not reliably exterior-then-hole, so an
        # odd number of containing rings is the correct test.
        if sum(in_ring(lon, lat, ring) for ring in boundary) % 2 == 1:
            return name
    return None


def model_bus(district: str, lon: float) -> str:
    """Map a Census district plus a longitude onto a model bus."""
    if district != "Ewa":
        return district
    return EWA_WEST if lon < EWA_SPLIT_LONGITUDE else EWA_CENTRAL


def haversine_miles(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = phi2 - phi1
    dlambda = math.radians(lon2 - lon1)
    a = math.sin(dphi / 2) ** 2 + math.cos(phi1) * math.cos(phi2) * math.sin(dlambda / 2) ** 2
    return 2 * EARTH_RADIUS_MILES * math.asin(math.sqrt(a))


def plant_coordinates() -> dict[int, tuple[float, float]]:
    plants = pd.read_excel(EIA860_PLANT, skiprows=1)
    plants = plants[plants["Plant Code"].isin(PLANT_CODES)]
    if len(plants) != len(PLANT_CODES):
        raise RuntimeError("EIA-860 is missing one of the modeled Oʻahu plants")
    return {
        int(plant["Plant Code"]): (float(plant["Latitude"]), float(plant["Longitude"]))
        for _, plant in plants.iterrows()
    }


def build_buses(coordinates: dict[int, tuple[float, float]]) -> tuple[pd.DataFrame, dict[str, list]]:
    subdivisions = fetch_json(
        CCD_GEOJSON, COUNTY_SUBDIVISION_LAYER, "GEOID,BASENAME,NAME,POP100", geometry=True
    )
    districts = {
        feature["properties"]["BASENAME"]: rings(feature["geometry"])
        for feature in subdivisions["features"]
    }
    official = {
        feature["properties"]["BASENAME"]: int(feature["properties"]["POP100"])
        for feature in subdivisions["features"]
    }

    tracts = fetch_json(
        TRACT_JSON, TRACT_LAYER, "GEOID,POP100,INTPTLAT,INTPTLON", geometry=False
    )
    # Per bus: [population-weighted latitude sum, longitude sum, tract population, district]
    weighted: dict[str, list] = {}
    for feature in tracts["features"]:
        attributes = feature["attributes"]
        pop = int(attributes["POP100"])
        if pop == 0:
            continue
        lat = float(attributes["INTPTLAT"])
        lon = float(attributes["INTPTLON"])
        district = locate(lon, lat, districts)
        if district is None:
            raise RuntimeError(f"tract {attributes['GEOID']} fell outside every district")
        bus = model_bus(district, lon)
        totals = weighted.setdefault(bus, [0.0, 0.0, 0, district])
        totals[0] += pop * lat
        totals[1] += pop * lon
        totals[2] += pop

    # Centroids use the tract weights; reported populations use the published CCD counts.
    # Tract internal points can land just across a CCD line, so tract sums drift from the
    # official totals by a few hundred people. Only the Ewa split needs the tract ratio.
    ewa_tract_total = weighted[EWA_WEST][2] + weighted[EWA_CENTRAL][2]
    rows = []
    for bus, (lat_sum, lon_sum, tract_pop, district) in weighted.items():
        if bus in (EWA_WEST, EWA_CENTRAL):
            population = official["Ewa"] * tract_pop / ewa_tract_total
        else:
            population = float(official[district])
        rows.append(
            {
                "bus": bus,
                "district": district,
                "population_2020": int(round(population)),
                "latitude": lat_sum / tract_pop,
                "longitude": lon_sum / tract_pop,
            }
        )

    kahe_lat, kahe_lon = coordinates[KAHE_PLANT_CODE]
    rows.append(
        {
            "bus": KAHE,
            "district": "Ewa",
            "population_2020": 0,
            "latitude": kahe_lat,
            "longitude": kahe_lon,
        }
    )

    buses = pd.DataFrame(rows)
    buses["load_share"] = buses.population_2020 / buses.population_2020.sum()
    buses["coordinate_source"] = "population-weighted 2020 census-tract centroid (TIGERweb)"
    buses.loc[buses.bus == KAHE, "coordinate_source"] = "EIA-860 2024 plant coordinate"
    buses["population_source"] = "U.S. Census 2020 P.L. 94-171 via TIGERweb county subdivisions"
    buses["load_share_source"] = "assumed: island net load allocated by resident population"
    buses.loc[buses.bus.isin([EWA_WEST, EWA_CENTRAL, KAHE]), "load_share_source"] = (
        f"assumed: Ewa CCD split at {EWA_SPLIT_LONGITUDE} W by census tract; Kahe modeled as a "
        "pure generation node"
    )
    return buses.sort_values("population_2020", ascending=False).reset_index(drop=True), districts


def build_generator_map(
    districts: dict[str, list], coordinates: dict[int, tuple[float, float]]
) -> pd.DataFrame:
    located = {}
    for code, (lat, lon) in coordinates.items():
        district = locate(lon, lat, districts)
        if district is None:
            raise RuntimeError(f"Plant {code} at ({lat}, {lon}) is outside every district")
        located[code] = (KAHE if code == KAHE_PLANT_CODE else model_bus(district, lon), lat, lon)

    fleet = pd.read_csv(FLEET)
    fleet["bus"] = fleet.plant_code.map(lambda code: located[int(code)][0])
    fleet["plant_latitude"] = fleet.plant_code.map(lambda code: located[int(code)][1])
    fleet["plant_longitude"] = fleet.plant_code.map(lambda code: located[int(code)][2])
    fleet["bus_source"] = (
        "EIA-860 2024 plant coordinates, point-in-polygon on Census CCDs, Ewa sub-divided"
    )
    return fleet[
        ["name", "plant_code", "bus", "plant_latitude", "plant_longitude", "p_max_mw", "bus_source"]
    ]


def build_branches(buses: pd.DataFrame) -> pd.DataFrame:
    point = buses.set_index("bus")[["latitude", "longitude"]].to_dict("index")
    rows = []
    for index, (from_bus, to_bus, corridor, circuits) in enumerate(BRANCHES, start=1):
        straight = haversine_miles(
            point[from_bus]["latitude"],
            point[from_bus]["longitude"],
            point[to_bus]["latitude"],
            point[to_bus]["longitude"],
        )
        length = straight * ROUTING_FACTOR
        reactance = X_OHM_PER_MILE * length / Z_BASE_OHM
        resistance = R_OHM_PER_MILE * length / Z_BASE_OHM
        rows.append(
            {
                "branch": index,
                "from_bus": from_bus,
                "to_bus": to_bus,
                "corridor": corridor,
                "circuits": circuits,
                "straight_line_mi": straight,
                "length_mi": length,
                "x_pu": reactance,
                "r_pu": resistance,
                "limit_mw": circuits * MW_PER_CIRCUIT,
                "transport_cost_usd_per_mwh": resistance * REFERENCE_LMP_USD_PER_MWH,
                "topology_source": "Hawaiian Electric Power Delivery: two corridors, north and south",
                "length_source": f"assumed: great-circle bus separation x {ROUTING_FACTOR} routing factor",
                "impedance_source": (
                    f"assumed: {X_OHM_PER_MILE} ohm/mi reactance and {R_OHM_PER_MILE} ohm/mi "
                    f"resistance at {BASE_KV:.0f} kV on a {BASE_MVA:.0f} MVA base"
                ),
                "limit_source": f"assumed: {MW_PER_CIRCUIT:.0f} MW per 138 kV circuit",
                "transport_cost_source": (
                    "assumed: per-unit resistance priced at the copper-plate marginal cost "
                    f"of ${REFERENCE_LMP_USD_PER_MWH:.2f}/MWh"
                ),
            }
        )
    return pd.DataFrame(rows)


def main() -> None:
    for path in [EIA860_PLANT, FLEET]:
        if not path.exists():
            raise FileNotFoundError(f"Missing {path}; run the earlier prepare scripts first")

    coordinates = plant_coordinates()
    buses, districts = build_buses(coordinates)
    generator_map = build_generator_map(districts, coordinates)
    branches = build_branches(buses)

    nodes, edges = len(buses), len(branches)
    loops = edges - nodes + 1
    if loops < 1:
        raise RuntimeError("network must contain at least one loop for DC-OPF to differ")
    if set(branches.from_bus) | set(branches.to_bus) != set(buses.bus):
        raise RuntimeError("branch endpoints and bus list disagree")

    PROCESSED.mkdir(parents=True, exist_ok=True)
    buses.round(6).to_csv(PROCESSED / "oahu_network_buses.csv", index=False)
    branches.round(6).to_csv(PROCESSED / "oahu_network_branches.csv", index=False)
    generator_map.round(6).to_csv(PROCESSED / "oahu_generator_bus_map.csv", index=False)

    served = generator_map.groupby("bus").p_max_mw.sum()
    print(f"Wrote {nodes} buses and {edges} branches ({loops} independent loops).")
    for _, bus in buses.iterrows():
        print(
            f"  {bus.bus:<12} {bus.load_share * 100:5.2f}% of load "
            f"{served.get(bus.bus, 0.0):8.1f} MW capacity"
        )


if __name__ == "__main__":
    main()
